[package]
name = "hgta1287dev/guarded-state-machine"
version = "1.0.1"
authors = ["hoamjg"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.3"
